[package]
edition = "2021"
name = "bevy_rts_cursor"
version = "0.1.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.9", features = ["dynamic"]}
bevy_mod_raycast = "0.7.0"

[dev-dependencies]
bevy-inspector-egui = "0.14.0"
